title: cellworld
description: A experimental platform for controllable, repeatable animal-robot interactions, within a space that can be varied from fully observable open arenas to partially observable cluttered arenas, or configured into conventional assays.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
# robot_assembly_link: https://github.com/cellworld/robot_assembly
# robot_assembly_link_text: Robot Assembly
# arena_assembly_link: https://github.com/cellworld/arena_assembly
# arena_assembly_link_text: Arena Assembly
paper_link: paper.html
paper_link_text: Cellworld Methods Paper
